In [1]:
# Name: Dhruv Kumar
# Roll No.: 24419CMP011
# Course: M.Sc. Computer Science
# Semester: 2nd

In [1]:
import cv2

# Read a color image
img = cv2.imread("D:\\Code\\cat.jpeg")

# Print size and data type of image file
print("Image Shape: ", img.shape)
print("Data Type: ", img.dtype, "\n")

# Convert the image into grayscale
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Displaying the array behind this image
print("Array Representation of Grayscale image:")
print(gray_img, "\n")

# Print the first row of the matrix as a list of integers
print("First row of grayscale image:")
print(list(gray_img[0]), "\n")

# Print a sub-region of the matrix (top-left 10x10 pixels)
print("Top-left 10x10 pixels of grayscale image:")
print(gray_img[:10, :10])

Image Shape:  (224, 225, 3)
Data Type:  uint8 

Array Representation of Grayscale image:
[[209 211 215 ... 227 227 225]
 [209 211 215 ... 226 226 223]
 [209 211 214 ... 225 226 221]
 ...
 [161 160 158 ... 208 210 207]
 [166 165 162 ... 210 212 211]
 [170 168 165 ... 211 213 214]] 

First row of grayscale image:
[209, 211, 215, 220, 225, 230, 234, 236, 239, 240, 240, 240, 241, 241, 241, 242, 239, 239, 239, 238, 238, 238, 237, 237, 240, 240, 240, 240, 240, 240, 240, 240, 242, 242, 242, 242, 242, 242, 242, 242, 239, 239, 239, 238, 237, 236, 236, 235, 236, 236, 235, 234, 234, 233, 232, 232, 231, 231, 231, 231, 231, 231, 231, 231, 228, 228, 228, 227, 227, 227, 226, 226, 227, 228, 228, 228, 229, 229, 229, 229, 232, 232, 231, 230, 229, 229, 228, 227, 228, 226, 223, 220, 215, 211, 208, 207, 200, 198, 195, 190, 183, 177, 171, 168, 152, 145, 134, 123, 116, 113, 114, 115, 106, 110, 116, 125, 134, 143, 149, 153, 170, 173, 179, 186, 194, 201, 207, 209, 224, 224, 224, 224, 224, 224, 224, 224, 223, 2

In [2]:
import cv2
import numpy as np

img1 = cv2.imread("D:\\Code\\lenna.jpeg")
img2 = cv2.imread('D:\\Code\\cat.jpeg')

# Resize images to match dimensions
img1 = cv2.resize(img1, (256, 256))
img2 = cv2.resize(img2, (256, 256))

# Perform arithmetic operations
addition = cv2.add(img1, img2)
subtraction = cv2.subtract(img1, img2)
multiplication = cv2.multiply(img1, img2)
average = (img1 // 2) + (img2 // 2)

# Display results
cv2.imshow("Image 1", img1)
cv2.imshow("Image 2", img2)
cv2.imshow("Addition", addition)
cv2.imshow("Subtraction", subtraction)
cv2.imshow("Multiplication", multiplication)
cv2.imshow("Averaging", average)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
import cv2

# Load a grayscale image
img = cv2.imread("D:\\Code\\cat.jpeg", cv2.IMREAD_GRAYSCALE)

# Ensure the image is 512x512
img = cv2.resize(img, (512, 512))

# Perform sub-sampling and store all versions
images = [img]
current_img = img 

for i in range(4):
    current_img = current_img[::2, ::2]
    images.append(current_img)

# Titles for each image
titles = ["512x512", "256x256", "128x128", "64x64", "32x32"]

# Display each image
for i in range(len(images)):
    cv2.imshow(titles[i], images[i])

cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
import cv2
import numpy as np

# Load a grayscale image
img = cv2.imread("D:\\Code\\cat.jpeg", cv2.IMREAD_GRAYSCALE)

# Ensure the image is 512x512
img = cv2.resize(img, (512, 512))

subsampled_imgs = [img]

# Subsampling
for i in range(4):
    img = img[::2, ::2]
    subsampled_imgs.append(img)

# Resampling
resampled_imgs = []

for i in subsampled_imgs[1:]:
    resampled = i.copy()
    while resampled.shape[0] < 512:
        resampled = np.repeat(resampled, 2, axis=0)
        resampled = np.repeat(resampled, 2, axis=1)
    resampled_imgs.append(resampled)

titles = ["256x256 -> 512x512", "128x128 -> 512x512", "64x64 -> 512x512", "32x32 -> 512x512"]

# Display resampled images
for i in range(4):
    cv2.imshow(titles[i], resampled_imgs[i])

cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
import cv2
import numpy as np

# Load grayscale image
img = cv2.imread("D:\\Code\\cat.jpeg", cv2.IMREAD_GRAYSCALE)

# Resize to 512x512 using cv2 just once
img = cv2.resize(img, (512, 512))

# Manual subsampling
subsampled_imgs = [img]
for _ in range(4):
    img = img[::2, ::2]
    subsampled_imgs.append(img)

# Manual resampling (nearest-neighbor upsampling without np.repeat)
resampled_imgs = []

for down in subsampled_imgs[1:]:  # Skip the original
    h, w = down.shape
    factor = 512 // h  # how much we need to upscale

    # Create an empty array of shape (512, 512)
    upsampled = np.zeros((512, 512), dtype=np.uint8)

    # Fill in each pixel by repeating the original pixels
    for i in range(h):
        for j in range(w):
            value = down[i, j]
            for x in range(i * factor, (i + 1) * factor):
                for y in range(j * factor, (j + 1) * factor):
                    upsampled[x, y] = value

    resampled_imgs.append(upsampled)

# Show images
titles = ["256x256 -> 512x512", "128x128 -> 512x512", "64x64 -> 512x512", "32x32 -> 512x512"]
for i in range(4):
    cv2.imshow(titles[i], resampled_imgs[i])

cv2.waitKey(0)
cv2.destroyAllWindows()