In [119]:
# (a) Generate input and labels

import numpy as np

np.random.seed(42)
m = 100
Dx = 200
Da1 = 20
C = 10

X = np.random.randn(m, Dx)

In [120]:
# (b) Generate random labels and convert to one-hot

labels = np.random.randint(0, C, size=(m,))
Y = np.zeros((m, C))
for i in range(m):
    Y[i, labels[i]] = 1

In [121]:
# (c) Initialize weights

W1 = np.random.randn(Dx, Da1) * 0.01
b1 = np.zeros((1, Da1))
W2 = np.random.randn(Da1, C) * 0.01
b2 = np.zeros((1, C))

In [122]:
def tanh(x):
    return np.tanh(x)

def tanh_derivative(x):
    return 1 - np.tanh(x) ** 2

def softmax(z):
    return np.exp(z) / np.sum(np.exp(z), axis=1, keepdims=True)

In [123]:
# (d) Forward Pass

def forward_pass(X, W1, b1, W2, b2):
    z1 = np.dot(X, W1) + b1
    a1 = tanh(z1)

    z2 = np.dot(a1, W2) + b2
    y_hat = softmax(z2)
    
    return z1, a1, z2, y_hat

In [124]:
# Backward Pass

def backward_pass(X, Y, z1, a1, z2, y_hat, W2):
    m = X.shape[0]
    dz2 = (y_hat - Y)
    dW2 = np.dot(a1.T, dz2)
    db2 = np.sum(dz2, axis=0, keepdims=True)

    da1 = np.dot(dz2, W2.T)
    dz1 = da1 * tanh_derivative(z1)
    dW1 = np.dot(X.T, dz1)
    db1 = np.sum(dz1, axis=0, keepdims=True)

    return dW1, db1, dW2, db2

In [125]:
# Update Parameters

def update_parameters(W1, b1, W2, b2, dW1, db1, dW2, db2, lr):
    W1 -= lr * dW1
    b1 -= lr * db1
    W2 -= lr * dW2
    b2 -= lr * db2
    return W1, b1, W2, b2

In [126]:
# (e) Cross-Entropy Loss

def cross_entropy_loss(Y, y_hat):
    epsilon = 1e-9
    sample_losses = -np.sum(Y * np.log(y_hat + epsilon), axis=1)
    return np.sum(sample_losses) / m

loss = cross_entropy_loss(Y, y_hat)
print(f"Average Cross-Entropy Loss: {loss:.4f}")

Average Cross-Entropy Loss: 0.0082


In [127]:
# Training Loop

epochs = 1000
lr = 0.1

for epoch in range(epochs):
    z1, a1, z2, y_hat = forward_pass(X, W1, b1, W2, b2)
    loss = cross_entropy_loss(Y, y_hat)
    if epoch % 100 == 0:
        print(f"Epoch {epoch}, Loss: {loss:.4f}")

    dW1, db1, dW2, db2 = backward_pass(X, Y, z1, a1, z2, y_hat, W2)
    W1, b1, W2, b2 = update_parameters(W1, b1, W2, b2, dW1, db1, dW2, db2, lr)

Epoch 0, Loss: 2.3022
Epoch 100, Loss: 0.0008
Epoch 200, Loss: 0.0004
Epoch 300, Loss: 0.0003
Epoch 400, Loss: 0.0002
Epoch 500, Loss: 0.0002
Epoch 600, Loss: 0.0001
Epoch 700, Loss: 0.0001
Epoch 800, Loss: 0.0001
Epoch 900, Loss: 0.0001


In [128]:
# (f) Performance Metrics

from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

y_pred = np.argmax(y_hat, axis=1)
y_true = np.argmax(Y, axis=1)

conf_mat = confusion_matrix(y_true, y_pred)
acc = accuracy_score(y_true, y_pred)
prec = precision_score(y_true, y_pred, average='macro')
rec = recall_score(y_true, y_pred, average='macro')
f1 = f1_score(y_true, y_pred, average='macro')

print("Confusion Matrix:\n", conf_mat)
print(f"Accuracy: {acc:.4f}")
print(f"Precision: {prec:.4f}")
print(f"Recall: {rec:.4f}")
print(f"F1 Score: {f1:.4f}")

Confusion Matrix:
 [[ 7  0  0  0  0  0  0  0  0  0]
 [ 0 11  0  0  0  0  0  0  0  0]
 [ 0  0 10  0  0  0  0  0  0  0]
 [ 0  0  0 14  0  0  0  0  0  0]
 [ 0  0  0  0  9  0  0  0  0  0]
 [ 0  0  0  0  0 15  0  0  0  0]
 [ 0  0  0  0  0  0  6  0  0  0]
 [ 0  0  0  0  0  0  0  9  0  0]
 [ 0  0  0  0  0  0  0  0  5  0]
 [ 0  0  0  0  0  0  0  0  0 14]]
Accuracy: 1.0000
Precision: 1.0000
Recall: 1.0000
F1 Score: 1.0000
